### ISSUE TITLE
Error while installing semantic.dashboard

### ISSUE THREAD

**Issue by shahreyar-abeer** [Appsilon/semantic.dashboard#149]
Hi guys,

I'm getting the following error while trying to install `semantic.dashboard`.
 Maybe it has something to do with `shiny.semantic` that you guys are heavily updating at the moment.
Please have a look at this.

Best regards,
Zauad

![image](https://user-images.githubusercontent.com/20732893/91655252-20f1bf80-ead1-11ea-8373-8eb234055b04.png)

**Comment by dokato** [comment]
Yes, thank you @shahreyar-abeer . The latest version of `shiny.semantic` required bigger changes, and we couldn't provide backward compatibility. We will be updating `semantic.dashboard` very soon accordingly. Stay tuned!

**Comment by shahreyar-abeer** [comment]
Okay thanks.

**Comment by dokato** [comment]
This should be fixed now.

**Comment by shahreyar-abeer** [comment]
Nope, not solved yet!

![image](https://user-images.githubusercontent.com/20732893/101715099-0910db00-3ac5-11eb-8210-7d61fd8297fb.png)
