### ISSUE TITLE
box width inside a tabBox

### ISSUE THREAD

**Issue by olangford** [Appsilon/semantic.dashboard#152]
Hi,

I've been working on converting my app to use `semantic.dashboard` and came across a bug in my code that I'm unable to resolve.  Apologizes in advance if I'm doing something wrong.

When using a `semantic.dashboard::box` inside a `semantic.dashboard::tabBox` the with of the box is always full width of the app.  Please see an example below:

```
library(shiny)
library(semantic.dashboard)

ui <- dashboardPage(
  dashboardHeader(color = "blue"),
  dashboardSidebar(side = "left", size = "thin", color = "teal",
                   sidebarMenu(
                     menuItem(tabName = "tab1", "Tab 1"),
                     menuItem(tabName = "tab2", "Tab 2"))),
  dashboardBody(
    tabItems(
      tabItem(
        tabName = "tab1",
        box(title = "Box1", width = 6, h2("Box width 6")),
        box(title = "Box2", width = 3, h2("Box width 3")),
        semantic.dashboard::tabBox(
          id = "tabset1",
          width = 16,
          tabs =
            list(
              list(
                menu = "Overview",
                content =
                  fluidPage("Overview",
                    fluidRow(
                      box(title = "Box3", width = 6, h2("Box width 6")),
                      box(title = "Box4", width = 3, h2("Box width 3"))
                    )
                  )
              )
            ),
            list(
              menu = "Sessions",
              content = fluidPage(
                h1("TEST")
              )
            )
          )
      )
    )
  )
)

server <- function(input, output) {
}

shinyApp(ui, server)
```

Appreciate any advice and all your work creating these R packages.  Thanks,

Oli

**Comment by dokato** [comment]
Thanks Oli for reporting that, this is definately some bug. We'll try to fix it soon.

**Comment by jchojna** [comment]
Hi Oli,
thank you for notifying this bug. It has been fixed on shiny.semantic github repo, so all you need to do is to install the latest version from develop: `remotes::install_github("Appsilon/shiny.semantic", ref="develop")`
On CRAN it will be updated in about 2 weeks.

We're sorry for the inconvenience and hope this issue didn't block you too much and now everything works fine!

**Comment by olangford** [comment]
No worries.   Thank you for your help!  Unfortunately I'm still experiencing the same behavior.  Here is my session info:

```
> devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Catalina 10.15.6      
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2020-12-19                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package            * version    date       lib source                                  
 assertthat           0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                          
 backports            1.1.5      2019-10-02 [1] CRAN (R 3.6.0)                          
 callr                3.4.3      2020-03-28 [1] CRAN (R 3.6.1)                          
 cli                  2.0.2      2020-02-28 [1] CRAN (R 3.6.0)                          
 colorspace           1.4-1      2019-03-18 [1] CRAN (R 3.6.0)                          
 crayon               1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                          
 crosstalk            1.1.0.1    2020-03-13 [1] CRAN (R 3.6.0)                          
 desc                 1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                          
 devtools             2.2.1      2019-09-24 [1] CRAN (R 3.6.0)                          
 digest               0.6.27     2020-10-24 [1] CRAN (R 3.6.2)                          
 dplyr                0.8.5      2020-03-07 [1] CRAN (R 3.6.0)                          
 DT                   0.12.1     2020-03-23 [1] Github (rstudio/DT@a3d0ec9)             
 ellipsis             0.3.0      2019-09-20 [1] CRAN (R 3.6.0)                          
 fansi                0.4.1      2020-01-08 [1] CRAN (R 3.6.0)                          
 fastmap              1.0.1      2019-10-08 [1] CRAN (R 3.6.0)                          
 fs                   1.5.0      2020-07-31 [1] CRAN (R 3.6.2)                          
 ggplot2              3.3.0      2020-03-05 [1] CRAN (R 3.6.0)                          
 glue                 1.4.2      2020-08-27 [1] CRAN (R 3.6.2)                          
 gtable               0.3.0      2019-03-25 [1] CRAN (R 3.6.0)                          
 htmltools            0.5.0.9003 2020-12-20 [1] Github (rstudio/htmltools@d18bd8e)      
 htmlwidgets          1.5.3      2020-12-10 [1] CRAN (R 3.6.2)                          
 httpuv               1.5.4      2020-06-06 [1] CRAN (R 3.6.2)                          
 jsonlite             1.7.2      2020-12-09 [1] CRAN (R 3.6.2)                          
 later                1.1.0.1    2020-06-05 [1] CRAN (R 3.6.2)                          
 leaflet              2.0.3      2019-11-16 [1] CRAN (R 3.6.0)                          
 lifecycle            0.2.0      2020-03-06 [1] CRAN (R 3.6.0)                          
 magrittr             2.0.1      2020-11-17 [1] CRAN (R 3.6.2)                          
 memoise              1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                          
 mime                 0.9        2020-02-04 [1] CRAN (R 3.6.0)                          
 munsell              0.5.0      2018-06-12 [1] CRAN (R 3.6.0)                          
 pillar               1.4.3      2019-12-20 [1] CRAN (R 3.6.0)                          
 pkgbuild             1.0.6      2019-10-09 [1] CRAN (R 3.6.0)                          
 pkgconfig            2.0.3      2019-09-22 [1] CRAN (R 3.6.0)                          
 pkgload              1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                          
 prettyunits          1.1.1      2020-01-24 [1] CRAN (R 3.6.0)                          
 processx             3.4.2      2020-02-09 [1] CRAN (R 3.6.0)                          
 promises             1.1.1      2020-06-09 [1] CRAN (R 3.6.2)                          
 ps                   1.3.2      2020-02-13 [1] CRAN (R 3.6.0)                          
 purrr                0.3.4      2020-04-17 [1] CRAN (R 3.6.2)                          
 R6                   2.5.0      2020-10-28 [1] CRAN (R 3.6.2)                          
 Rcpp                 1.0.5      2020-07-06 [1] CRAN (R 3.6.2)                          
 remotes              2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                          
 rlang                0.4.9      2020-11-26 [1] CRAN (R 3.6.2)                          
 rprojroot            1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                          
 rsconnect            0.8.16     2019-12-13 [1] CRAN (R 3.6.1)                          
 rstudioapi           0.11       2020-02-07 [1] CRAN (R 3.6.1)                          
 scales               1.1.0      2019-11-18 [1] CRAN (R 3.6.0)                          
 semantic.dashboard * 0.1.8      2020-10-19 [1] CRAN (R 3.6.2)                          
 sessioninfo          1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                          
 shiny              * 1.5.0.9004 2020-10-11 [1] Github (rstudio/shiny@ec18ef6)          
 shiny.semantic     * 0.4.2      2020-12-20 [1] Github (Appsilon/shiny.semantic@09708a6)
 stringi              1.4.6      2020-02-17 [1] CRAN (R 3.6.0)                          
 stringr              1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                          
 testthat             2.3.2      2020-03-02 [1] CRAN (R 3.6.0)                          
 tibble               2.1.3      2019-06-06 [1] CRAN (R 3.6.0)                          
 tidyselect           1.0.0      2020-01-27 [1] CRAN (R 3.6.0)                          
 usethis              1.5.1      2019-07-04 [1] CRAN (R 3.6.0)                          
 withr                2.3.0      2020-09-22 [1] CRAN (R 3.6.2)                          
 xtable               1.8-4      2019-04-21 [1] CRAN (R 3.6.0)                          

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

Appreciate any thoughts you may have on what I'm doing incorrect.

**Comment by olangford** [comment]
Hi, 

Just an additional note, removing the `fluidPage("Overview",`allows the boxes to be their set width.  

I also noted that when I clicked minimize on the box, I was unable maximize it back.  Not sure if this is related.

**Comment by dokato** [comment]
For setting the width, you need to remove `fluidPage`, which is `Shiny` specific function, not semantic, so it adds some tags from bootstrap to `div` classes that break the DOM structure for Fomantic css:

```r
                content = fluidRow(
                              box(title = "Box3", width = 6, h2("Box width 6")),
                              box(title = "Box4", width = 3, h2("Box width 3"))
                            )
```

> I also noted that when I clicked minimize on the box, I was unable maximize it back. Not sure if this is related.

This is another thing, we'll check that. I created a separate issue #157.

Also, note that `semantic.dashboard` v 0.2.0 is available with quite a few fixes.
